### ISSUE TITLE
hiprand ordering 

### ISSUE THREAD

**Issue by jinz2014** [ROCm/hipRAND#75]
Building a HIP program shows the following errors. Users don't need to call rocrand APIs.  Thanks.

unknown type name 'hiprandOrdering_t'

use of undeclared identifier 'hiprandSetGeneratorOrdering'

use of undeclared identifier 'HIPRAND_ORDERING_QUASI_DEFAULT'; did you mean 'ROCRAND_ORDERING_QUASI_DEFAULT'?

use of undeclared identifier 'HIPRAND_ORDERING_PSEUDO_DEFAULT'; did you mean 'ROCRAND_ORDERING_PSEUDO_DEFAULT'

**Comment by Snektron** [comment]
Hi, the definitions are indeed missing. I'm adding it internally, it should come to a PR soon-ish. Sorry for the delay.

**Comment by jinz2014** [comment]
Okay. Thanks.

**Comment by ppanchad-amd** [comment]
@jinz2014 Can you please confirm if this is fixed in ROCm 6.2? If so, please close the ticket. Thanks!
