### ISSUE TITLE
rocm-5.7.0 tag does not match the release/rocm-rel-5.7 branch

### ISSUE THREAD

**Issue by trixirt** [ROCm/hipRAND#85]
rocm-5.7.0 tag is the same for rocm-5.6.0 and changes have been made since then

> git checkout release/rocm-rel-5.7 
> git log
commit b7b91006d19c84cb742c75f19157ece72ab8f9ca (HEAD -> release/rocm-rel-5.7, origin/release/rocm-rel-5.7)
Author: Robson Lemos <31936621+RobsonRLemos@users.noreply.github.com>
Date:   Wed Sep 13 11:39:14 2023 -0600

    Add struct prefix (#37) (#73)

commit 97ba7e9128655cc106402a291ea3faabbbc2d02f
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Thu Sep 7 14:11:19 2023 -0600

    Bump rocm-docs-core from 0.20.0 to 0.24.0 in /docs/.sphinx (#72)
    
    * Bump rocm-docs-core from 0.20.0 to 0.24.0 in /docs/.sphinx
    
    Bumps [rocm-docs-core](https://github.com/RadeonOpenCompute/rocm-docs-core) from 0.20.0 to 0.24.0.
    - [Release notes](https://github.com/RadeonOpenCompute/rocm-docs-core/releases)
    - [Changelog](https://github.com/RadeonOpenCompute/rocm-docs-core/blob/develop/CHANGELOG.md)
    - [Commits](https://github.com/RadeonOpenCompute/rocm-docs-core/compare/v0.20.0...v0.24.0)
    
    ---
    updated-dependencies:
    - dependency-name: rocm-docs-core
      dependency-type: direct:production
      update-type: version-update:semver-minor
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>
    
    * Update requirements.in
    
    * Update requirements.txt
    
    ---------
    
    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
    Co-authored-by: Sam Wu <sam.wu2@amd.com>

commit c92081c43a0f989b2ca90f0084ecb66595c6393c (origin/release-staging/rocm-rel-5.7)
Author: Eiden Yoshida <47196116+eidenyoshida@users.noreply.github.com>
Date:   Wed Jun 28 11:53:18 2023 -0600

    Add **gfx94x** targets (#54)

commit 8babdbe0cf4dc330c9ec5a0231ac059187a7bc8a (tag: **rocm-5.7.0**, tag: rocm-5.6.1, tag: rocm-5.6.0, tag: rocm-5.5.1, tag: rocm-5.5.0, origin/master)
Merge: 5bbb30c d429334
Author: Stanley Tsang <stanley.tsang@amd.com>
Date:   Tue Dec 13 09:57:20 2022 -0700

    Merge pull request #24 from ROCmSoftwarePlatform/develop_stream_20221114
    
    Develop Stream 2022-11-14

**Comment by lawruble13** [comment]
This is actually intended. The `release/rocm-5.7` branch is intended to represent the latest code for ROCm 5.7.x (and thus includes code for later releases under the same minor version), and the tags are used to track the contents of each individual release.

Prior to ROCm 6.0, hipRAND was packaged alongside rocRAND for distribution, and included into rocRAND via a submodule. The submodule reference of hipRAND was not updated in rocRAND for ROCm 5.7, hence why the tag is the same as for ROCm 5.6.0. This is also why hipRAND does not have any GitHub releases prior to 6.0.
